name: Update Daily Progress

on:
  schedule:
    - cron: "30 1 * * *"  # Runs daily at 7:00 AM IST (1:30 UTC)
  workflow_dispatch:

jobs:
  update-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run progress updater
        run: python scripts/update_progress.py

      - name: Commit changes
        run: |
          git config --global user.name "vishal-wahatule-git"
          git config --global user.email "vishal.vahatule02@gmail.com"
          git add README.md
          git commit -m "chore: update daily progress [bot]" || echo "No changes to commit"
          git push
